---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoding-transformer
  namespace: toolset
  annotations:
    configmap.reloader.stakater.com/reload: "encoding-transformer-cm,rsa-secret,encoding-transformer-charset"
spec:
  selector:
    matchLabels:
      app: encoding-transformer
  replicas: 1
  template:
    metadata:
      labels:
        app: encoding-transformer
    spec:
      volumes:
        - name: config
          configMap:
            name: encoding-transformer-cm
        - name: charset
          configMap:
            name: encoding-transformer-charset
        - name: rsa
          secret:
            secretName: rsa-secret
            items:
              - key: pub.pem
                path: pub.pem
      containers:
      - name: encoding-transformer
        image: snowphoenix/toolset_encodetransformer
        args:
          - "java"
          - "-jar"
          - "/usr/local/ToolSetEncodeTransformer.jar"
          - "--spring.config.location=/usr/share/encoding/application.yaml"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /usr/share/encoding
          - name: charset
            mountPath: /usr/share/encoding/charSet
          - name: rsa
            mountPath: /usr/share/encoding/pem
        readinessProbe:
          httpGet:
            port: 80
            path: /health/get
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            port: 80
            path: /health/get
          timeoutSeconds: 2
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          
---
apiVersion: v1
kind: Service
metadata:
  name: encoding-transformer
  namespace: toolset
spec:
  selector:
    app: encoding-transformer
  type: NodePort
  ports:
  - port: 9002
    targetPort: 80
