---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
  namespace: toolset
data:
  redis.conf: |-
    always-show-logo yes
    port 6379
    maxmemory 128mb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: toolset
  annotations:
    configmap.reloader.stakater.com/reload: "redis-cm"
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: config
          configMap:
            name: redis-cm
      containers:
      - name: redis
        image: redis
        command:
          - "redis-server"
          - "/user/local/redis/redis.conf"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: config
            mountPath: /user/local/redis/redis.conf
            subPath: redis.conf
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 6379
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          
---