---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-center
  namespace: toolset
  annotations:
    configmap.reloader.stakater.com/reload: "user-center-cm,rsa-secret"
spec:
  selector:
    matchLabels:
      app: user-center
  replicas: 1
  template:
    metadata:
      labels:
        app: user-center
    spec:
      volumes:
        - name: config
          configMap:
            name: user-center-cm
        - name: rsa
          secret:
            secretName: rsa-secret
            items:
              - key: pub.pem
                path: pub.pem
              - key: pri.pkcs8.pem
                path: pri.pkcs8.pem
      containers:
      - name: user-center
        image: snowphoenix/toolset_usercenter
        command:
          # - "ls"
          # - "/usr/share/usercenter"
          # - "cat"
          # - "/usr/share/usercenter/pem/pub.pem"
          - "java"
          - "-jar"
          - "/usr/local/ToolSetUserCenter.jar"
          - "--spring.config.location=/usr/share/usercenter/application.yaml"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /usr/share/usercenter
          - name: rsa
            mountPath: /usr/share/usercenter/pem
        readinessProbe:
          httpGet:
            port: 80
            path: /health/get
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            port: 80
            path: /health/get
          timeoutSeconds: 2
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          
---
apiVersion: v1
kind: Service
metadata:
  name: user-center
  namespace: toolset
spec:
  selector:
    app: user-center
  type: NodePort
  ports:
  - port: 9002
    targetPort: 80
